import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import NavBar from '@/app/ui/nav-bar'
import { auth0 } from "./lib/auth0";
import Landing from "./ui/landing";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SocialApp",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth0.getSession();

  if (!session) {
    return (
      <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <a href="/auth/login">Logueate fistro</a>
        <Landing />
      </body>
      </html>
    )
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <h1>{session.user.name}</h1>
        <a href="/auth/logout">Deslogueate fistro</a>
        <NavBar></NavBar>
        {children}
      </body>
    </html>
  );
}
